title: Machine Learning in Production
theme: jekyll-theme-minimal
logo: poster_2020_v2.jpg
description: A 24h course to get better at shipping Machine Learning projects
twitter_handle: ArnauTibau
google_analytics: UA-155495148-1
